# Generated by Django 4.2.3 on 2025-01-19 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhosWhoApp', '0002_staffprofile_about_me_staffprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='custom_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
