# Generated by Django 4.2.3 on 2025-01-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhosWhoApp', '0003_staffprofile_custom_status_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
