# Generated by Django 4.2.3 on 2025-01-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhosWhoApp', '0004_staffprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
