# Generated by Django 4.2.3 on 2025-01-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhosWhoApp', '0005_alter_staffprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='monday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
