# Generated by Django 4.2.3 on 2025-01-23 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhosWhoApp', '0007_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
