# Generated by Django 4.2.3 on 2025-01-23 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhosWhoApp', '0008_staffprofile_bookmarked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
