# Generated by Django 4.2.3 on 2025-01-25 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhosWhoApp', '0009_alter_staffprofile_bookmarked_by_delete_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='profile_views',
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateField(auto_now_add=True)),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='WhosWhoApp.staffprofile')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('staff_profile', 'visitor', 'viewed_at')},
            },
        ),
    ]
