# Generated by Django 4.2.3 on 2025-01-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhosWhoApp', '0010_remove_staffprofile_profile_views_profileview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(max_length=500),
        ),
    ]
